### ISSUE TITLE
Proto definition modifications

### ISSUE THREAD

**Issue by Gabrinthei** [provenance-io/metadata-asset-model#2]
## Summary

1. Adjust Money and Rate validations
2. Loan type definition to specify super and sub types
3. Add document metadata field to loan_state

## Problem Definition

1. `tech.figure.util.v1beta1.Money` should allow negative values
2. Remove `tech.figure.util.v1beta1.Rate`'s max limit
3. Define a structured LoanType utility message

## Proposal

```
message Money {
  double amount   = 1;
  string currency = 2 [(validate.rules).string.len = 3]; // ISO 4217 3-digit currency code
}
```

```
message Rate {
  double value = 1 [(validate.rules).double = {gte: 0}];
}
```

```
message LoanType {
  string supertype = 1 [(validate.rules).string.min_len = 1]; // The supertype of loan (e.g. MORTGAGE, HELOC, PERSONAL_LOAN, AUTO_LOAN)
  string subtype   = 2 [(validate.rules).string.min_len = 1]; // The subtype of the loan (e.g. JUMBO, REFI, PARENT_REFI, DRAW)
}
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rpatel-figure** [comment]
Looks like this was addressed in #3 and #15, so closing
